name: bob.bio.face-ongoing
channels:
- https://www.idiap.ch/software/bob/conda
- defaults
dependencies:
- bob=4.0.1
- tensorflow=1.4.1
- bob.buildout
- ipython
- bob.bio.base
- bob.bio.face
- bob.bio.gmm
- bob.bio.video
- bob.db.lfw
- gridtk
- bob.ip.tensorflow_extractor
- bob.db.mnist
- bob.db.ijba
- bob.db.lfw
- bob.db.mobio
- bob.ip.caffe_extractor
- bob.bio.caffe_face
- sphinx_rtd_theme
- torch == 0.3.1
- pytorch 0.3  # [linux]
- torchvision 0.1.8  # [linux]
