name: bob.bio.face-ongoing
channels:
- https://www.idiap.ch/software/bob/conda
- defaults
dependencies:
- _license=1.1=py27_1
- alabaster=0.7.10=py27_0
- anaconda-client=1.6.3=py27_0
- anaconda=custom=py27_0
- anaconda-navigator=1.6.2=py27_0
- anaconda-project=0.6.0=py27_0
- asn1crypto=0.22.0=py27_0
- astroid=1.4.9=py27_0
- astropy=1.3.2=np112py27_0
- babel=2.4.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- beautifulsoup4=4.6.0=py27_0
- bitarray=0.8.1=py27_0
- bkcharts=0.2=py27_0
- blaze=0.10.1=py27_0
- bleach=1.5.0=py27_0
- bokeh=0.12.6=py27_0
- boost=1.61.0=py27_0
- boto=2.46.1=py27_0
- bottleneck=1.2.1=np112py27_0
- bzip2=1.0.6=3
- caffe=1.0.0rc5=np112py27_0
- cairo=1.14.8=0
- cdecimal=2.3=py27_2
- cffi=1.10.0=py27_0
- chardet=3.0.3=py27_0
- click=6.7=py27_0
- cloog=0.18.0=0
- cloudpickle=0.2.2=py27_0
- clyent=1.2.2=py27_0
- cmake=3.6.3=0
- colorama=0.3.9=py27_0
- configparser=3.5.0=py27_0
- contextlib2=0.5.5=py27_0
- coverage=4.3.4=py27_0
- cryptography=1.8.1=py27_0
- curl=7.52.1=0
- cycler=0.10.0=py27_0
- cython=0.25.2=py27_0
- cytoolz=0.8.2=py27_0
- dask=0.14.3=py27_1
- datashape=0.5.4=py27_0
- dbus=1.10.10=0
- decorator=4.0.11=py27_0
- distributed=1.16.3=py27_0
- docopt=0.6.2=py27_0
- docutils=0.13.1=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_0
- et_xmlfile=1.0.1=py27_0
- expat=2.1.0=0
- fastcache=1.0.2=py27_1
- flask=0.12.2=py27_0
- flask-cors=3.0.2=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.1.1=py27_0
- gcc=4.8.5=7
- get_terminal_size=1.0.0=py27_0
- gevent=1.2.1=py27_0
- gflags=2.1.2=0
- glib=2.50.2=1
- glog=0.3.4=0
- gmp=6.1.0=0
- greenlet=0.4.12=py27_0
- grin=1.2.1=py27_3
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np112py27_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py27_1
- html5lib=0.999=py27_0
- icu=54.1=0
- idna=2.5=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.18=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- isl=0.12.2=0
- isort=4.2.5=py27_0
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jdcal=1.3=py27_0
- jedi=0.10.2=py27_2
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=5.0.1=py27_0
- jupyter_console=5.1.0=py27_0
- jupyter_core=4.3.0=py27_0
- lazy-object-proxy=1.2.2=py27_0
- leveldb=1.19=1
- libffi=3.2.1=1
- libgcc=4.8.5=2
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.18.0=py27_0
- lmdb=0.9.18=0
- locket=0.2.0=py27_1
- lxml=3.7.3=py27_0
- markupsafe=0.23=py27_2
- matplotlib=2.0.2=np112py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.1=0
- mkl-service=1.1.2=py27_3
- mock=2.0.0=py27_0
- mpc=1.0.3=0
- mpfr=3.1.5=0
- mpmath=0.19=py27_1
- msgpack-python=0.4.8=py27_0
- multipledispatch=0.4.9=py27_0
- navigator-updater=0.1.0=py27_0
- nbconvert=5.2.1=py27_0
- nbformat=4.3.0=py27_0
- ncurses=5.9=10
- networkx=1.11=py27_0
- nltk=3.2.3=py27_0
- nose=1.3.7=py27_1
- notebook=5.0.0=py27_0
- numba=0.33.0=np112py27_0
- numexpr=2.6.2=np112py27_0
- numpy=1.12.1=py27_0
- numpydoc=0.6.0=py27_0
- odo=0.5.0=py27_1
- olefile=0.44=py27_0
- openblas=0.2.19=0
- openpyxl=2.4.7=py27_0
- openssl=1.0.2l=0
- packaging=16.8=py27_0
- pandas=0.20.1=np112py27_0
- pandocfilters=1.4.1=py27_0
- pango=1.40.3=1
- partd=0.3.8=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- patsy=0.4.1=py27_0
- pbr=1.10.0=py27_0
- pcre=8.39=1
- pep8=1.7.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=4.1.1=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pkg-config=0.28=1
- ply=3.10=py27_0
- prompt_toolkit=1.0.14=py27_0
- protobuf=3.2.0=py27_0
- psutil=5.2.2=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.33=py27_0
- pycairo=1.10.0=py27_0
- pycosat=0.6.2=py27_0
- pycparser=2.17=py27_0
- pycrypto=2.6.1=py27_6
- pycurl=7.43.0=py27_2
- pyflakes=1.5.0=py27_0
- pygments=2.2.0=py27_0
- pylint=1.6.4=py27_1
- pyodbc=4.0.16=py27_0
- pyopenssl=17.0.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- pytables=3.3.0=np112py27_0
- pytest=3.0.7=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- python-gflags=2.0=py27_0
- python-leveldb=0.194=py27_1
- pytz=2017.2=py27_0
- pywavelets=0.5.2=np112py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=4
- qtawesome=0.4.4=py27_0
- qtconsole=4.3.0=py27_0
- qtpy=1.2.1=py27_0
- readline=6.2=2
- requests=2.14.2=py27_0
- rope=0.9.4=py27_1
- ruamel_yaml=0.11.14=py27_1
- scandir=1.5=py27_0
- scikit-image=0.13.0=np112py27_0
- scikit-learn=0.18.1=np112py27_1
- scipy=0.19.0=np112py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snappy=1.1.4=0
- snowballstemmer=1.2.1=py27_0
- sortedcollections=0.5.3=py27_0
- sortedcontainers=1.5.7=py27_0
- sphinx=1.5.6=py27_0
- sphinx_rtd_theme=0.2.4=py27_0
- spyder=3.1.4=py27_0
- sqlalchemy=1.1.9=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.8.0=np112py27_0
- subprocess32=3.2.7=py27_0
- sympy=1.0=py27_0
- tblib=1.3.2=py27_0
- tensorflow=1.1.0=np112py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.18=0
- toolz=0.8.2=py27_0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- unicodecsv=0.14.1=py27_0
- unixodbc=2.3.4=0
- wcwidth=0.1.7=py27_0
- werkzeug=0.12.2=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=2.0.0=py27_0
- wrapt=1.10.10=py27_0
- xlrd=1.0.0=py27_0
- xlsxwriter=0.9.6=py27_0
- xlwt=1.2.0=py27_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zict=0.1.2=py27_0
- zlib=1.2.8=3
- bob=3.0.0=py27_0
- bob-devel=2017.06.20=np112py27_0
- bob.bio.base=3.1.2=py_0
- bob.bio.caffe_face=1.1.0=py_0
- bob.bio.face=3.2.0=py_0
- bob.bio.gmm=3.0.2=py_0
- bob.bio.spear=3.1.0=py_0
- bob.bio.video=3.2.0=py_0
- cyvlfeat=0.4.5=np112py27_2
- dlib=19.0=np112py27_1
- ffmpeg=2.8.10=4
- giflib=5.1.4=3
- gridtk=1.4.3=py_0
- ipdb=0.10.2=py27_0
- libblitz=0.10=3
- libmatio=1.5.6=3
- libogg=1.3.2=0
- libsvm=3.21=3
- menpo=0.8.1=np112py27_0
- menpofit=0.5.0=py27_0
- menpowidgets=0.3.0p6=py27_0
- mne=0.14.1=np112py27_0
- opencv=3.1.0=np112py27_4
- openfst=1.6.1=0
- pathlib=1.0=py27_0
- pkgtools=0.7.3=py27_0
- pyedflib=0.1.9=np112py27_0
- schema=0.6.5=py27_0
- sox=14.4.2=5
- speex=1.2.0=0
- toolchain=2.3.2=0
- vlfeat=0.9.20=3
- x264=20131217=3
- zc.buildout=2.9.2=py27_0
- sphinx_rtd_theme=py27_0
